name: Build and Static Analysis

on:
  push:

jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: reneplattner/msp430-gcc:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: make

      - name: Static analysis
        run: make cppcheck
