name: Build and Static Analysis

on:
  push:

jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: reneplattner/msp430-gcc:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format files
        working-directory: ${{ github.workspace }}
        run: make format && git diff --quiet

      - name: Static analysis
        working-directory: ${{ github.workspace }}
        run: make cppcheck TOOLS_PATH=/opt/tools

      - name: Build project
        working-directory: ${{ github.workspace }}
        run: make TOOLS_PATH=/opt/tools

