name: Build and Static Analysis

on:
  push:

defaults:
  run:
    working-directory: ${{ github.workspace }}

jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: reneplattner/msp430-gcc:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: format files
        run: make format && git diff --quiet

      - name: Static analysis
        run: make cppcheck TOOLS_PATH=/opt/tools

      - name: Build project
        run: make TOOLS_PATH=/opt/tools

